Repository IBM/ibm-monitoring-grafana-operator, pull requests merged in 2020-04, with the labels that each got.

#4 add dependency request and add healthcheck dependency annotation
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.8.1/ibm-grafana-operator.v1.8.1.clusterserviceversion.yaml
  pkg/controller/model/grafana_deployment.go
Labels: approved, size/S

#6 scc
  build/dashboards/kubernetes-monitoring.json
  build/dashboards/nginx-ingress-controller.json
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.8.1/ibm-grafana-operator.v1.8.1.clusterserviceversion.yaml
  deploy/role.yaml
Labels: approved, size/XL

#7 update for ibm certification
  README.md
  deploy/crds/monitoringcontroller.cloud.ibm.com_monitoringdashboards_crd.yaml
  deploy/crds/operator.ibm.com_grafanas_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_grafana_cr.yaml
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.8.0/ibm-grafana-operator.v1.8.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.8.0/monitoringcontroller.cloud.ibm.com_monitoringdashboards_crd.yaml
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.8.0/operator.ibm.com_grafanas_crd.yaml
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.8.1/ibm-grafana-operator.v1.8.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.8.1/monitoringcontroller.cloud.ibm.com_monitoringdashboards_crd.yaml
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.8.1/operator.ibm.com_grafanas_crd.yaml
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.9.0/ibm-monitoring-grafana-operator.v1.9.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.9.0/monitoringcontroller.cloud.ibm.com_monitoringdashboards_crd.yaml
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.9.0/operator.ibm.com_grafanas_crd.yaml
  deploy/olm-catalog/monitoringdashboard-crd.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
Labels: approved, size/L

#9 fix typo when changing for ibm certification
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.8.0/ibm-grafana-operator.v1.8.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.8.1/ibm-grafana-operator.v1.8.1.clusterserviceversion.yaml
Labels: approved, size/S

#10 remove default imagePullSecret; update description; update push-csv.sh
  common/scripts/push-csv.sh
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.9.0/ibm-monitoring-grafana-operator.v1.9.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#11 IBM certification:use latest image
  deploy/operator.yaml
Labels: approved, size/XS
