Repository IBM/ibm-monitoring-grafana-operator, pull requests merged in 2020-05, with the labels that each got.

#12 use operator pod environment variables for image references
  deploy/crds/operator.ibm.com_v1alpha1_grafana_cr.yaml
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.9.0/ibm-monitoring-grafana-operator.v1.9.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/model/constants.go
  pkg/controller/model/grafana_dashboard.go
  pkg/controller/model/grafana_deployment.go
  pkg/controller/model/grafana_router.go
  pkg/controller/model/utils.go
Labels: approved, size/M

#13 update productVersion of metering annotation to 3.4.0
  deploy/operator.yaml
  pkg/controller/model/grafana_deployment.go
Labels: approved, size/XS

#14 update operand images
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.9.0/ibm-monitoring-grafana-operator.v1.9.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/S

#15 Operand image update
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.9.0/ibm-monitoring-grafana-operator.v1.9.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#16 update for ibm certificate
  deploy/crds/monitoringcontroller.cloud.ibm.com_monitoringdashboards_crd.yaml
  deploy/crds/operator.ibm.com_grafanas_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_grafana_cr.yaml
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.8.0/ibm-grafana-operator.v1.8.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.8.0/monitoringcontroller.cloud.ibm.com_monitoringdashboards_crd.yaml
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.8.0/operator.ibm.com_grafanas_crd.yaml
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.8.1/ibm-grafana-operator.v1.8.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.8.1/monitoringcontroller.cloud.ibm.com_monitoringdashboards_crd.yaml
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.8.1/operator.ibm.com_grafanas_crd.yaml
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.9.0/ibm-monitoring-grafana-operator.v1.9.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.9.0/monitoringcontroller.cloud.ibm.com_monitoringdashboards_crd.yaml
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.9.0/operator.ibm.com_grafanas_crd.yaml
  deploy/olm-catalog/monitoringdashboard-crd.yaml
  deploy/role.yaml
  deploy/service_account.yaml
  pkg/controller/dashboards/init.go
  pkg/controller/model/grafana_deployment.go
  pkg/controller/model/grafana_ingress.go
  pkg/controller/model/grafana_service.go
  pkg/controller/model/utils.go
  pkg/controller/model/volume_source.go
Labels: approved, size/M

#17 make grafana operator depend on exporter and prometheusext
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.9.0/ibm-monitoring-grafana-operator.v1.9.0.clusterserviceversion.yaml
Labels: approved, size/XS

#18 add beta channel
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.9.0/ibm-monitoring-grafana-operator.v1.9.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-monitoring-grafana-operator/ibm-monitoring-grafana-operator.package.yaml
Labels: approved, size/XS

#19 add scripts to protect csv not changed. only dev csv can be changed
  common/scripts/.githooks/pre-commit
  common/scripts/csv-protect.py
  common/scripts/push-csv.sh
Labels: approved, size/L

#21 change to container probs; update memory limits because of power needs more memory
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.9.1/ibm-monitoring-grafana-operator.v1.9.1.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/model/grafana_dashboard.go
  pkg/controller/model/grafana_deployment.go
Labels: approved, size/XS

#20 improve CSV description and readme with template
  README.md
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.9.1/ibm-monitoring-grafana-operator.v1.9.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#22 Beta 1.9.1
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.9.1/ibm-monitoring-grafana-operator.v1.9.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-monitoring-grafana-operator/ibm-monitoring-grafana-operator.package.yaml
Labels: approved, size/XS
