Repository IBM/ibm-monitoring-grafana-operator, pull requests merged in 2021-04, with the labels that each got.

#99 2.5.11 version of icp-management-ingress digest updated
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.10.5/ibm-monitoring-grafana-operator.v1.10.5.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: size/XS

#100 ingress digest refresh
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.10.5/ibm-monitoring-grafana-operator.v1.10.5.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: size/XS

#101 updated quay images for vascan fixes
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.10.5/ibm-monitoring-grafana-operator.v1.10.5.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: size/S

#102 dashboard-controller:v1.2.2-build.4 digest updated
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.10.5/ibm-monitoring-grafana-operator.v1.10.5.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: size/XS

#98 Removal of Use verb for grafana operator (2Q)
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.12.0/ibm-monitoring-grafana-operator.v1.12.0.clusterserviceversion.yaml
  deploy/role.yaml
Labels: size/S

#103 Update readme
  README.md
Labels: lgtm, size/XS

#104 Revert "Update readme"
  README.md
Labels: size/XS

#105 CSV Update (Dummy)
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.12.0/ibm-monitoring-grafana-operator.v1.12.0.clusterserviceversion.yaml
Labels: size/XS

#106 operand auto-sha update
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.12.0/ibm-monitoring-grafana-operator.v1.12.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: lgtm, size/S
