Repository IBM/ibm-monitoring-grafana-operator, pull requests merged in 2021-06, with the labels that each got.

#109 grafana-operator to clean old CS Monitoring resources
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.12.0/ibm-monitoring-grafana-operator.v1.12.0.clusterserviceversion.yaml
  deploy/role.yaml
  pkg/controller/grafana/grafana_reconcile.go
  pkg/controller/model/cleanup_csmonitoring.go
  pkg/controller/model/constants.go
Labels: approved, size/L

#110 fix cv linter issue:CSVHasValidRelatedImages
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.12.0/ibm-monitoring-grafana-operator.v1.12.0.clusterserviceversion.yaml
Labels: approved, size/S

#111 increment operand img versions
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.12.0/ibm-monitoring-grafana-operator.v1.12.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/M

#112 updated OWNERS file
  OWNERS
Labels: approved, size/XS

#113 Router container liveness/readiness probe timeout introduced
  pkg/controller/model/grafana_router.go
Labels: approved, lgtm, size/XS

#114 Copyright year updated #45123
  Makefile
  pkg/apis/operator/v1alpha1/grafana_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/artifacts/entrypoint.go
  pkg/controller/artifacts/grafanaConfig.go
  pkg/controller/grafana/grafana_reconcile.go
  pkg/controller/model/cert.go
  pkg/controller/model/cleanup_csmonitoring.go
  pkg/controller/model/constants.go
  pkg/controller/model/grafana_dashboard.go
  pkg/controller/model/grafana_deployment.go
  pkg/controller/model/grafana_router.go
  pkg/controller/model/utils.go
  pkg/controller/model/volume_source.go
  version/version.go
Labels: approved, lgtm, size/M

#117 updated minKubeVersion as 1.19 in operator csv #47503
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.13.0/ibm-monitoring-grafana-operator.v1.13.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.13.0/monitoringcontroller.cloud.ibm.com_monitoringdashboards_crd.yaml
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.13.0/operator.ibm.com_grafanas_crd.yaml
  version/version.go
Labels: lgtm, size/XL

#118 CRD api movement to v1 changes
  deploy/crds/monitoringcontroller.cloud.ibm.com_monitoringdashboards_crd.yaml
  deploy/crds/operator.ibm.com_grafanas_crd.yaml
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.13.0/monitoringcontroller.cloud.ibm.com_monitoringdashboards_crd.yaml
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.13.0/operator.ibm.com_grafanas_crd.yaml
  deploy/olm-catalog/ibm-monitoring-grafana-operator/ibm-monitoring-grafana-operator.package.yaml
Labels: approved, lgtm, size/XXL

#120 remove stale properties
  deploy/crds/operator.ibm.com_v1alpha1_grafana_cr.yaml
Labels: approved, size/XS
