Repository IBM/ibm-monitoring-grafana-operator, pull requests merged in 2022-07, with the labels that each got.

#171 Dummy commit to trigger lstr build
  README.md
Labels: approved, size/XS

#172 Remove replaces in CSV
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.24.0/ibm-monitoring-grafana-operator.v1.24.0.clusterserviceversion.yaml
Labels: approved, size/XS, lgtm

#173 Provide forward and backwards compatibility to CRDs #54043
  deploy/crds/monitoringcontroller.cloud.ibm.com_monitoringdashboards_crd.yaml
  deploy/crds/operator.ibm.com_grafanas_crd.yaml
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.24.0/monitoringcontroller.cloud.ibm.com_monitoringdashboards_crd.yaml
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.24.0/operator.ibm.com_grafanas_crd.yaml
Labels: size/XS, lgtm

#174 Provide forward and backwards compatibility to CRDs #54043
  deploy/crds/monitoringcontroller.cloud.ibm.com_monitoringdashboards_crd.yaml
  deploy/crds/operator.ibm.com_grafanas_crd.yaml
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.24.0/monitoringcontroller.cloud.ibm.com_monitoringdashboards_crd.yaml
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.24.0/operator.ibm.com_grafanas_crd.yaml
Labels: size/XS, lgtm

#176 LTSR 3.19.3 version bump up
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.23.2/ibm-monitoring-grafana-operator.v1.23.2.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.23.2/monitoringcontroller.cloud.ibm.com_monitoringdashboards_crd.yaml
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.23.2/operator.ibm.com_grafanas_crd.yaml
  deploy/olm-catalog/ibm-monitoring-grafana-operator/ibm-monitoring-grafana-operator.package.yaml
  deploy/operator.yaml
  version/version.go
Labels: size/XL, lgtm

#177 Fix the version in the latest CSV
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.23.2/ibm-monitoring-grafana-operator.v1.23.2.clusterserviceversion.yaml
Labels: approved, size/XS, lgtm
