Repository IBM/ibm-monitoring-grafana-operator, pull requests merged in 2022-11, with the labels that each got.

#188 Failure threshold introduced and increased timeout for readiness/liveness probe
  pkg/controller/model/grafana_router.go
Labels: approved, size/XS, lgtm

#190 Operand version updated for 3.22.0
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.26.0/ibm-monitoring-grafana-operator.v1.26.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: size/S

#191 Update operand version for 3.19.7
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.23.6/ibm-monitoring-grafana-operator.v1.23.6.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.23.6/monitoringcontroller.cloud.ibm.com_monitoringdashboards_crd.yaml
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.23.6/operator.ibm.com_grafanas_crd.yaml
  deploy/olm-catalog/ibm-monitoring-grafana-operator/ibm-monitoring-grafana-operator.package.yaml
  deploy/operator.yaml
  version/version.go
Labels: size/XL

#194 new prow cluster
  common/Makefile.common.mk
  triggerfile
Labels: approved, size/XS

#195 new prow cluster for ltsr release
  README.md
  common/Makefile.common.mk
Labels: size/XS
