Repository IBM/ibm-monitoring-grafana-operator, pull requests merged in 2022-03, with the labels that each got.

#154 go version updated to 1.17.7 for eus
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
Labels: size/M

#156 bump version for CD 3.17.0
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.21.0/ibm-monitoring-grafana-operator.v1.21.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.21.0/monitoringcontroller.cloud.ibm.com_monitoringdashboards_crd.yaml
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.21.0/operator.ibm.com_grafanas_crd.yaml
  deploy/olm-catalog/ibm-monitoring-grafana-operator/ibm-monitoring-grafana-operator.package.yaml
  deploy/operator.yaml
  version/version.go
Labels: size/XL, lgtm

#157 bump version for CD 3.17.0-2
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.21.0/ibm-monitoring-grafana-operator.v1.21.0.clusterserviceversion.yaml
Labels: size/S, lgtm

#158 update operator img with tag
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.21.0/ibm-monitoring-grafana-operator.v1.21.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#155 [DONOTMERGE]Notification about OCP app monitoring enabled is removed #51656
  pkg/controller/grafana/grafana_reconcile.go
Labels: approved, size/XS
