Repository IBM/ibm-monitoring-grafana-operator, pull requests merged in 2023-01, with the labels that each got.

#198 trigger build
  README.md
Labels: approved, size/XS

#199 operand and operator version bumup for 3.24.0 #56850
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.28.0/ibm-monitoring-grafana-operator.v1.28.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.28.0/monitoringcontroller.cloud.ibm.com_monitoringdashboards_crd.yaml
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.28.0/operator.ibm.com_grafanas_crd.yaml
  deploy/olm-catalog/ibm-monitoring-grafana-operator/ibm-monitoring-grafana-operator.package.yaml
  deploy/operator.yaml
  version/version.go
Labels: size/XL

#200 operand version bumup in operator for 3.19.8 #56315
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.23.7/ibm-monitoring-grafana-operator.v1.23.7.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: size/S

#201 Artifactory image location updated for Monitoring #56862
  Makefile
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
  common/config/.hadolint.yml
  common/scripts/config_docker.sh
Labels: size/S

#202 Artifactory image location updated for Monitoring #56862
  Makefile
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
  common/config/.hadolint.yml
  common/scripts/config_docker.sh
Labels: size/S

#203 move version from 1.28.0 to 1.27.1
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.27.1/ibm-monitoring-grafana-operator.v1.27.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.27.1/monitoringcontroller.cloud.ibm.com_monitoringdashboards_crd.yaml
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.27.1/operator.ibm.com_grafanas_crd.yaml
  deploy/olm-catalog/ibm-monitoring-grafana-operator/ibm-monitoring-grafana-operator.package.yaml
  deploy/operator.yaml
  version/version.go
Labels: approved, size/S
